title: My blog
description: My very nice blog
author: "H S"

base_url: ""

# Minima social links
github_username: lunarhunar
linkedin_username: lunarhunar

category-list: [posts, pages, images, static]

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/about.md
  - _pages/archive.md

#Static pages live here e.g. about.md
include: ['_pages','_posts']

markdown: kramdown

plugins:
  - jekyll-feed

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
