title: My blog
description: My very nice blog
author: "H S"

base_url: ""

# Minima social links
github_username: lunarhunar
linkedin_username: lunarhunar
rss: rss

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/about.md
  - _pages/archive.md

include:
    - _pages
    - _posts

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
